import streamlit as st


st.sidebar.markdown("# Cosmological datasets for geometric deep learning")
st.sidebar.write("\n\n")
FP = st.sidebar.button("Front page")
st.sidebar.write("\n\n")
st.sidebar.markdown("---")
st.sidebar.write("Choose the dataset:")
PC = st.sidebar.button("Point clouds")
MT = st.sidebar.button("Merger trees")
st.sidebar.markdown("---")
glosary = st.sidebar.button("Glosary")
team = st.sidebar.button("Team")

# Show introduction only if no button is clicked
if not (PC or MT or glosary or team):
    st.markdown("""
    ### Cosmological datasets for geometric deep learning

    We provide two kind of cosmological datasets to train and benchmark models:
    - **Point clouds**. These are collections of points representing galaxies or halos in different universes.
    - **Merger trees**. These are graphs $G=(V,E)$ representing the past time evolution of a dark matter halo. 

    It is important to understand the difference between **dark matter halos** and **galaxies**.
    """, unsafe_allow_html=True)

    col1, col2 = st.columns([1, 2])
    with col1:
        st.image("plots/halo.png", caption="Galaxies inside a halo", width=230)
    with col2:
        st.markdown("""
        - **Dark matter halos** (or simply *halos*) are massive, invisible structures made of normal and dark matter.
        - They act as the **gravitational wells** where galaxies are born and evolve.
        - A single halo can host **one or more galaxies**, and their evolution is tightly connected.
        - Computationally, it is easier to simulate dark matter halos than galaxies.

        This distinction is fundamental for building accurate physical models.
        """)


if PC:

    st.title('Point clouds')

    col1, col2 = st.columns([1, 2])
    with col1:
        st.image("plots/point_cloud.png", width=230)
    with col2:
        st.markdown("""Point clouds are set of points, $\{x_i\}_{i=1}^N$ with $x_i\in\mathbb{R}^d$, representing dark matter halos or galaxies in different universes. These point clouds are generated by running state-of-the-art numerical cosmological simulations with different initial conditions and different compositions of the Universe.""")
    st.markdown("""We provide three different types of points clouds:

- **Quijote**. These are dark matter halos from cosmological N-body simulations that only account for gravity. They sample a big volume and contain some of the largest halos in their respective universes. Each Quijote simulations contains around 100,000 dark matter halos.
- **CAMELS-SAM**. These are galaxies obtained by combining cosmological N-body simulations with semi-analytics models of galaxy formation. The sample a volume 1000x smaller than Quijote but their galaxies are quite representative of the standard galaxies observed in the universe.
- **CAMELS**. These are galaxies obtained from full cosmological hydrodynamic simulations. They sample a volume 64x smaller than CAMELS-SAM, but their galaxies are simulated with a model much sophisticated than those of CAMELS-SAM.

The figure below compares the sizes of the point clouds from the different datasets.
""")

    st.image('plots/Data.png', width=700)
    


if MT:

    st.title('Merger trees')

    st.markdown("""Marger trees are directed acyclic graphs, $(V,E)$, where
- Nodes represent individual dark matter halos (or subhalos) at a specific point in cosmic time (or redshift). $V=\{h_1, h_2, h_3,...h_n\}$. Typical node properties are mass, concetration, positions...etc.

- Edges represent progenitor-descendant relationships, pointing from a progenitor halo (earlier time) to its descendant halo (later time). $E=\{(h_i,h_j)|h_i\leftarrow h_j\}$. 

The diagram below shows a merger tree from a CAMELS-SAM simulation. The left-most red point represents a dark matter halo at current time from a CAMELS-SAM simulation. From left to right we go further back in time. The sequence with the red dots is called the main branch. When two or more nodes join, it means that physically, two or several halos has merged to produce a bigger halo.""")

    st.image("plots/merger_tree.png", use_container_width=True)

    
if team:

    #st.title('Graphs4cosmo team')
    #st.text('\n\n')
    st.image('photos/team.png')
    #image_paths = ['photos/Teresa.jpeg', 'photos/Richard.jpg', 'photos/Jun-Young.jpeg',
    #                'photos/Lucia.jpg', 'photos/Charles.png', 'photos/Adrian.jpg',
    #                'photos/Lawrence.jpg', 'photos/Paco.png']
    #captions = ['Ningyuan (Teresa) Huang (Flatiron)',
    #            'Richard Stiskalek (Flatiron/Oxford)',
    #            'Jun-Young Lee (Seoul)',
    #            'Lucia Perez (Flatiron)',
    #            'Charles Margossian (Flatiron)',
    #            'Adrian Bayer (Princeton/Flatiron)',
    #            'Lawrence Saul (Flatiron)',
    #            'Francisco Villaescusa-Navarro (Flatiron)']

    #for row in range(2):
    #    cols = st.columns(4)
    #    for col in range(4):
    #        idx = row * 4 + col
    #        with cols[col]:
    #            st.image(image_paths[idx], use_container_width=True)
    #            st.caption(captions[idx])
            
                
